import { Component } from '@angular/core';
import { AgGridAngular } from 'ag-grid-angular';
import { ColDef, ModuleRegistry, AllCommunityModule } from 'ag-grid-community';

ModuleRegistry.registerModules([AllCommunityModule]);

@Component({
  selector: 'app-table-grid',
  imports: [AgGridAngular],
  templateUrl: './table-grid.component.html',
  styleUrl: './table-grid.component.css'
})
export class TableGridComponent {
  public colDef: ColDef[] = [
    { field: "make" },
    { field: "model" },
    { field: "price" },
    { field: "electric" }
  ];

  public rowData = [
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
    {"make": "Tesla", "model": "Model x", "price": 99999, "electric": true},
    {"make": "Ford", "model": "sdfg", "price": 0, "electric": true},
    {"make": "Toyuta", "model": "Model x", "price": 101010101010, "electric": false},
    {"make": "BMW", "model": "Model x", "price": 1010, "electric": true},
    {"make": "Fiat", "model": "Model x", "price": 123456789, "electric": false},
  ];
}
